# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[ 1.5946e+15, -1.6213e-07,  2.3517e+19],
        [ 4.5859e-41,  2.2533e+19,  4.5859e-41],
        [ 2.0907e+30, -5.0809e+07,  2.2538e+19],
        [ 4.5859e-41,  2.2533e+19,  4.5859e-41],
        [ 2.3499e-01, -2.2264e+07,  2.2538e+19]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0919, 0.3005, 0.0738],
        [0.2688, 0.0571, 0.4964],
        [0.3461, 0.5209, 0.1323],
        [0.8329, 0.0020, 0.1261],
        [0.9069, 0.2970, 0.9580]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [5]:
x[1:3] = 2
print(x)

tensor([[0.0919, 0.3005, 0.0738],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.8329, 0.0020, 0.1261],
        [0.9069, 0.2970, 0.9580]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [12]:
# 1.
torch.Tensor(2, 17)

tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31, 7.2148e+22, 2.5226e-18, 6.4825e-10,
         1.0527e-11, 3.0880e-09, 2.5935e-09, 4.1880e-11, 2.6557e-06, 2.9575e-18,
         6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27, 6.1972e-04],
        [7.2443e+22, 1.7728e+28, 7.0367e+22, 1.1970e+22, 4.2656e-08, 1.0425e-11,
         6.6015e-07, 6.8621e-07, 6.8984e-07, 2.5206e-09, 2.0662e+20, 1.7585e-04,
         2.4289e-18, 7.7052e+31, 1.9447e+31, 5.0207e+28, 4.6695e+21]])

In [13]:
# 2.
torch.FloatTensor(3, 1)

tensor([[3.9862e+19],
        [4.5859e-41],
        [3.9862e+19]])

In [21]:
# 3.
torch.full((5, 2, 1), 7., dtype=torch.long)

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])

In [2]:
torch.ByteTensor(5,)


tensor([240, 110,  92,  16, 131], dtype=torch.uint8)

In [50]:
# 4.
bt = torch.ones(5,dtype=torch.uint8)
bt[1:-1] = 0
print(bt)

tensor([1, 0, 0, 0, 1], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [33]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.6394, 0.6921, 0.3011],
        [2.3676, 2.2448, 2.9787],
        [2.0195, 2.9456, 2.1194],
        [1.2959, 0.8115, 0.2785],
        [1.5956, 1.1675, 1.1809]])


### 2.2 Addition: syntax 2

In [34]:
print(torch.add(x, y))

tensor([[0.6394, 0.6921, 0.3011],
        [2.3676, 2.2448, 2.9787],
        [2.0195, 2.9456, 2.1194],
        [1.2959, 0.8115, 0.2785],
        [1.5956, 1.1675, 1.1809]])


### 2.3 Addition: giving an output tensor

In [35]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.6394, 0.6921, 0.3011],
        [2.3676, 2.2448, 2.9787],
        [2.0195, 2.9456, 2.1194],
        [1.2959, 0.8115, 0.2785],
        [1.5956, 1.1675, 1.1809]])


### 2.4 Addition: in-place

adds `x`to `y`

In [36]:
y.add_(x)
print(y)

tensor([[0.6394, 0.6921, 0.3011],
        [2.3676, 2.2448, 2.9787],
        [2.0195, 2.9456, 2.1194],
        [1.2959, 0.8115, 0.2785],
        [1.5956, 1.1675, 1.1809]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [37]:
print(x[:, 1])

tensor([0.3005, 2.0000, 2.0000, 0.0020, 0.2970])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [43]:
# 1.
torch.Tensor.mul(x, y)

tensor([[3.7588e-02, 1.4394e-01, 6.6867e-03],
        [1.1211e+01, 1.0079e+01, 1.7745e+01],
        [8.1571e+00, 1.7353e+01, 8.9840e+00],
        [1.3988e+00, 1.3171e-03, 9.7849e-03],
        [2.3090e+00, 4.0480e-01, 1.3360e+00]])

In [44]:
# 2.
torch.Tensor.mul_(x, y)

tensor([[3.7588e-02, 1.4394e-01, 6.6867e-03],
        [1.1211e+01, 1.0079e+01, 1.7745e+01],
        [8.1571e+00, 1.7353e+01, 8.9840e+00],
        [1.3988e+00, 1.3171e-03, 9.7849e-03],
        [2.3090e+00, 4.0480e-01, 1.3360e+00]])

In [45]:
# 3.
torch.Tensor.div_(x, y)

tensor([[5.8785e-02, 2.0796e-01, 2.2210e-02],
        [4.7353e+00, 4.4897e+00, 5.9574e+00],
        [4.0391e+00, 5.8911e+00, 4.2389e+00],
        [1.0794e+00, 1.6231e-03, 3.5128e-02],
        [1.4470e+00, 3.4673e-01, 1.1313e+00]])

In [47]:
# 4.
torch.Tensor.mul(torch.Tensor(2, 4), torch.Tensor(4, 2).T)

tensor([[1.0056e+02, 0.0000e+00, 1.0646e+14, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [48]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [49]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [51]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [52]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [56]:
# 1.
tt = torch.ones(5, 2)
print(tt)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [57]:
# 2.
na = tt.numpy()
print(na)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [59]:
# 3.
tt = torch.from_numpy(na)
print(tt)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [60]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
